image: Visual Studio 2017

environment:
  matrix:
  - solution_path: homework4\ParsingTree\ParsingTree.sln  

before_build:
 - nuget restore %solution_path%

build_script:
  - msbuild %solution_path%

test_script:
  - vstest.console /logger:Appveyor **\*.Tests.dll