image: Visual Studio 2017

environment:
  matrix:
  - solution_path: homework4/ParsingTree/ParsingTree.sln
  - test_path: homework4/ParsingTree.Tests/bin/Debug/ParsingTree.Tests.dll

before_build:
 - nuget restore %solution_path%

build_script:
  - msbuild %solution_path%

test_script:
  - vstest.console /logger:Appveyor %test_path%