image: Visual Studio 2017

environment:
  matrix:
  - solution_path: homework7\GenericSet\GenericSet.sln
  - solution_path: homework7\GenericList\GenericList.sln
  - solution_path: homework1\FibonacciFactorial.sln
  - solution_path: homework1\matrix_sort.sln
  - solution_path: homework1\QuickSort.sln
  - solution_path: homework2\HashTable\HashTable.sln
  - solution_path: homework2\SinglyLinkedList\SinglyLinkedList.sln


before_build:
 - nuget restore %solution_path%

build_script:
  - msbuild %solution_path%